# Generated by Django 4.1 on 2022-11-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='serial',
            field=models.CharField(max_length=30),
        ),
    ]
