# Generated by Django 4.1 on 2022-11-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitar', '0002_alter_equipo_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='area',
            field=models.CharField(choices=[('Prestamo', 'Prestamo'), ('Área Comercial', 'Área Comercial'), ('Área Financiera', 'Área Financiera'), ('Área Administrativa', 'Área Administrativa'), ('Área Academica', 'Área Academica')], default='Prestamo', max_length=150),
        ),
    ]
