# Generated by Django 4.1 on 2022-11-25 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApplyNowApp', '0001_initial'),
        ('Solicitar', '0003_equipo_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('accesorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Solicitar.accesorio')),
                ('entretenimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Solicitar.entretenimiento')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Solicitar.equipo')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApplyNowApp.perfil')),
            ],
            options={
                'verbose_name': 'solicitud',
                'verbose_name_plural': 'solicitudes',
            },
        ),
    ]
