# Generated by Django 4.1 on 2022-11-25 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitar', '0004_solicitudes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudes',
            old_name='perfil',
            new_name='user',
        ),
    ]
