# Generated by Django 4.1 on 2022-11-25 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Solicitar', '0005_rename_perfil_solicitudes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
