# Generated by Django 4.1 on 2022-12-05 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitar', '0008_historial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historial',
        ),
    ]
