# Generated by Django 4.1 on 2022-12-05 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitar', '0009_delete_historial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solicitudes',
        ),
    ]
