# Generated by Django 4.1 on 2022-12-05 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitar', '0011_solicitudesequipos_solicitudesentretenimientos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudesaccesorios',
            options={'verbose_name': 'solicitud', 'verbose_name_plural': 'solicitudes de accesorios'},
        ),
        migrations.AlterModelOptions(
            name='solicitudesbalones',
            options={'verbose_name': 'solicitud', 'verbose_name_plural': 'solicitudes de balones'},
        ),
        migrations.AlterModelOptions(
            name='solicitudesentretenimientos',
            options={'verbose_name': 'solicitud', 'verbose_name_plural': 'solicitudes de entretenimientos'},
        ),
        migrations.AlterModelOptions(
            name='solicitudesequipos',
            options={'verbose_name': 'solicitud', 'verbose_name_plural': 'solicitudes de equipos'},
        ),
    ]
