# Generated by Django 4.1.3 on 2022-12-09 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Solicitar', '0013_alter_solicitudesequipos_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='historialEquipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('cargador', models.BooleanField()),
                ('area', models.CharField(choices=[('Prestamo', 'Prestamo'), ('Área Comercial', 'Área Comercial'), ('Área Financiera', 'Área Financiera'), ('Área Administrativa', 'Área Administrativa'), ('Área Academica', 'Área Academica')], max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historial',
                'verbose_name_plural': 'historial de equipos',
            },
        ),
        migrations.CreateModel(
            name='historialEntretenimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historial',
                'verbose_name_plural': 'historial de entretenimientos',
            },
        ),
        migrations.CreateModel(
            name='historialBalones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historial',
                'verbose_name_plural': 'historial de balones',
            },
        ),
        migrations.CreateModel(
            name='historialAccesorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historial',
                'verbose_name_plural': 'historial de accesorios',
            },
        ),
    ]
