# Generated by Django 4.1.3 on 2022-12-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitar', '0014_historialequipos_historialentretenimientos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudesaccesorios',
            name='validacion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='solicitudesbalones',
            name='validacion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='solicitudesentretenimientos',
            name='validacion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='solicitudesequipos',
            name='validacion',
            field=models.BooleanField(default=True),
        ),
    ]
