# Generated by Django 4.1.3 on 2022-12-09 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitar', '0015_solicitudesaccesorios_validacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudesentretenimientos',
            name='validacion',
        ),
    ]
