# Generated by Django 4.1.3 on 2022-12-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplyNowApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ValidacioiniBalon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ValidacioiniEquipo',
            field=models.BooleanField(default=False),
        ),
    ]
