# Generated by Django 4.1.3 on 2022-12-09 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApplyNowApp', '0002_perfil_validacioinibalon_perfil_validacioiniequipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='ValidacioiniBalon',
            new_name='ValidacionBalon',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='ValidacioiniEquipo',
            new_name='ValidacionEquipo',
        ),
    ]
